---
- name: Install default Apache Web Server
  hosts: all
  become: yes

  
  tasks:
  - block:
      - name: Install Apache WebServer
        yum: name=httpd state=latest

      - name: Start Apache and Unable it on the every boot
        service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat" 
