---
- name: Create folder 1
  file:
    path: /home/secret/folder1
    state: directory
    mode: 0755

- name: Create folder 2
  file:
    path: /home/secret/folder2
    state: directory
    mode: 0755
