---
# tasks file for deploy_apache_web
- block: # ====== Block for CentOs ======
    - name: Install Apache WebServer for CentOS
      yum: name=httpd state=latest
    - name: Start Web Server service for CentOS
      service: name=httpd state=started enabled=yes
  when: ansible_os_family == "RedHat"

- block: # ====== Block for UBUNTU ======
    - name: Install Apache Web Server for Ubuntu
      apt: name=apache2 state=latest
    - name: Start Web Server service for Ubuntu
      service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"

- name: Generate INDEX HTML file
  template: src=index.j2 dest={{ destin_folder }}/index.html mode=0555
  notify:
    - Restart Apache CentOS
    - Restart Apache Ubuntu

- name: Copy MyHomePage to Servers
  copy: src={{ item }} dest={{ destin_folder }} mode=0555
  loop:
    - "1.jpg"
    - "2.jpg"
    - "104.jpg"
    - "calf.jpg"
  notify:
    - Restart Apache CentOS
    - Restart Apache Ubuntu
